import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "SEO Dashboard — SmartCalc MY Admin",
  description: "Internal SEO monitoring dashboard for SmartCalc MY.",
  robots: { index: false, follow: false },
};

// ---------------------------------------------------------------------------
// Static data — update after each content push
// ---------------------------------------------------------------------------

const SITE_STATS = {
  totalPages: 66,
  guides: 44,
  calculators: 9,
  staticPages: 8, // home, about, calculators, contact, privacy, terms, author, /_not-found
  sitemapUrls: 66,
  lastUpdated: "2026-06-22 (Phase 3.1 — orphan fix)",
};

const INTEGRATIONS = [
  { name: "Google Analytics (GA4)", status: "active", detail: "GoogleAnalytics component with afterInteractive strategy. Tracks pageviews via usePathname.", color: "green" },
  { name: "Google AdSense", status: "active", detail: "ca-pub-1748627778343988 — native <script> in <head>. Verified placement in .next/server/app/index.html.", color: "green" },
  { name: "Google Search Console", status: "pending", detail: "Submit sitemap at /sitemap.xml after each deploy. Verify via DNS TXT or HTML file method.", color: "yellow" },
  { name: "Sitemap", status: "active", detail: "/sitemap.xml — auto-generated by Next.js from app/sitemap.ts. 66 URLs across all pages.", color: "green" },
  { name: "robots.txt", status: "active", detail: "/robots.txt — auto-generated, allows all crawlers, points to sitemap.", color: "green" },
  { name: "Canonical URLs", status: "active", detail: "All pages export alternates.canonical. Set via metadata in each page.tsx.", color: "green" },
  { name: "JSON-LD Schema", status: "active", detail: "All 44 guides have Article + FAQPage + BreadcrumbList @graph. Calculators have WebApplication schema.", color: "green" },
  { name: "Open Graph / Twitter Cards", status: "active", detail: "All pages export openGraph and twitter metadata. og-image.png is 1200×630.", color: "green" },
];

const CALCULATORS = [
  { slug: "/bmi-calculator", title: "BMI Calculator", keywords: ["BMI calculator Malaysia", "Asian BMI thresholds"] },
  { slug: "/salary-calculator-malaysia", title: "Salary Calculator Malaysia", keywords: ["salary calculator Malaysia", "take home pay Malaysia"] },
  { slug: "/loan-calculator", title: "Loan Calculator", keywords: ["loan calculator Malaysia", "monthly instalment calculator"] },
  { slug: "/income-tax-calculator-malaysia", title: "Income Tax Calculator Malaysia", keywords: ["income tax calculator Malaysia", "LHDN calculator"] },
  { slug: "/epf-calculator-malaysia", title: "EPF Calculator Malaysia", keywords: ["EPF calculator Malaysia", "KWSP calculator"] },
  { slug: "/pcb-calculator-malaysia", title: "PCB Calculator Malaysia", keywords: ["PCB calculator Malaysia", "MTD calculator"] },
  { slug: "/dsr-calculator-malaysia", title: "DSR Calculator Malaysia", keywords: ["DSR calculator Malaysia", "debt service ratio calculator"] },
  { slug: "/socso-calculator-malaysia", title: "SOCSO Calculator Malaysia", keywords: ["SOCSO calculator Malaysia", "PERKESO calculator"] },
  { slug: "/eis-calculator-malaysia", title: "EIS Calculator Malaysia", keywords: ["EIS calculator Malaysia", "SIP calculator"] },
];

// Internal link analysis — inbound links from other SITE pages (not external)
// Counts how many other guides/calculators link TO each page
const INTERNAL_LINK_ANALYSIS: {
  slug: string;
  title: string;
  inbound: number;
  outbound: number;
  risk: "ok" | "low" | "orphan";
}[] = [
  // Phase 1 guides (original) — well interlinked
  { slug: "/guides/epf-contribution-guide-malaysia", title: "EPF Contribution Guide", inbound: 6, outbound: 4, risk: "ok" },
  { slug: "/guides/epf-withdrawal-guide-malaysia", title: "EPF Withdrawal Guide", inbound: 4, outbound: 3, risk: "ok" },
  { slug: "/guides/how-much-epf-at-30-malaysia", title: "How Much EPF at 30", inbound: 5, outbound: 3, risk: "ok" },
  { slug: "/guides/how-to-calculate-salary-after-epf", title: "Calculate Salary After EPF", inbound: 3, outbound: 3, risk: "ok" },
  { slug: "/guides/salary-deductions-explained-malaysia", title: "Salary Deductions Explained", inbound: 4, outbound: 4, risk: "ok" },
  { slug: "/guides/pcb-vs-income-tax-malaysia", title: "PCB vs Income Tax", inbound: 3, outbound: 3, risk: "ok" },
  { slug: "/guides/how-pcb-tax-works-malaysia", title: "How PCB Tax Works", inbound: 5, outbound: 3, risk: "ok" },
  { slug: "/guides/how-to-reduce-income-tax-malaysia", title: "How to Reduce Income Tax", inbound: 3, outbound: 3, risk: "ok" },
  { slug: "/guides/what-salary-to-afford-house-malaysia", title: "What Salary to Afford House", inbound: 3, outbound: 3, risk: "ok" },
  { slug: "/guides/housing-loan-eligibility-malaysia", title: "Housing Loan Eligibility", inbound: 4, outbound: 3, risk: "ok" },
  { slug: "/guides/how-to-improve-loan-approval-malaysia", title: "Improve Loan Approval", inbound: 2, outbound: 3, risk: "low" },
  { slug: "/guides/personal-loan-vs-housing-loan-malaysia", title: "Personal Loan vs Housing Loan", inbound: 2, outbound: 3, risk: "low" },
  { slug: "/guides/what-is-dsr-malaysia", title: "What Is DSR Malaysia", inbound: 7, outbound: 3, risk: "ok" },
  { slug: "/guides/how-to-calculate-bmi-malaysia", title: "How to Calculate BMI", inbound: 2, outbound: 2, risk: "low" },
  // SOCSO / EIS
  { slug: "/guides/socso-contribution-table-malaysia", title: "SOCSO Contribution Table", inbound: 4, outbound: 3, risk: "ok" },
  { slug: "/guides/eis-contribution-table-malaysia", title: "EIS Contribution Table", inbound: 4, outbound: 3, risk: "ok" },
  // EPF advanced
  { slug: "/guides/epf-dividend-history-malaysia", title: "EPF Dividend History", inbound: 5, outbound: 3, risk: "ok" },
  // Credit
  { slug: "/guides/how-to-check-ccris-malaysia", title: "How to Check CCRIS", inbound: 5, outbound: 3, risk: "ok" },
  { slug: "/guides/how-to-improve-ctos-score-malaysia", title: "Improve CTOS Score", inbound: 5, outbound: 3, risk: "ok" },
  // Phase 1 new guides
  { slug: "/guides/first-home-buyer-guide-malaysia", title: "First Home Buyer Guide", inbound: 5, outbound: 4, risk: "ok" },
  { slug: "/guides/car-loan-eligibility-malaysia", title: "Car Loan Eligibility", inbound: 4, outbound: 3, risk: "ok" },
  { slug: "/guides/personal-loan-guide-malaysia", title: "Personal Loan Guide", inbound: 3, outbound: 3, risk: "ok" },
  { slug: "/guides/emergency-fund-malaysia", title: "Emergency Fund Malaysia", inbound: 3, outbound: 3, risk: "ok" },
  { slug: "/guides/rm3000-salary-budget-plan-malaysia", title: "RM3,000 Budget Plan", inbound: 4, outbound: 4, risk: "ok" },
  // Phase 2 guides — fewer inbound links (newer content)
  { slug: "/guides/epf-retirement-calculator-guide-malaysia", title: "EPF Retirement Calculator Guide", inbound: 2, outbound: 4, risk: "low" },
  { slug: "/guides/salary-to-buy-rm300k-house-malaysia", title: "Salary for RM300k House", inbound: 2, outbound: 3, risk: "low" },
  { slug: "/guides/salary-to-buy-rm500k-house-malaysia", title: "Salary for RM500k House", inbound: 2, outbound: 3, risk: "low" },
  { slug: "/guides/fixed-deposit-vs-epf-malaysia", title: "Fixed Deposit vs EPF", inbound: 2, outbound: 3, risk: "low" },
  { slug: "/guides/asb-vs-epf-malaysia", title: "ASB vs EPF Malaysia", inbound: 2, outbound: 3, risk: "low" },
  { slug: "/guides/best-budgeting-apps-malaysia", title: "Best Budgeting Apps", inbound: 1, outbound: 3, risk: "low" },
  { slug: "/guides/credit-card-eligibility-malaysia", title: "Credit Card Eligibility", inbound: 4, outbound: 2, risk: "ok" },
  { slug: "/guides/credit-score-malaysia-explained", title: "Credit Score Malaysia Explained", inbound: 4, outbound: 4, risk: "ok" },
  { slug: "/guides/how-to-increase-credit-score-malaysia", title: "How to Increase Credit Score", inbound: 4, outbound: 4, risk: "ok" },
  { slug: "/guides/ptptn-repayment-guide-malaysia", title: "PTPTN Repayment Guide", inbound: 4, outbound: 2, risk: "ok" },
  { slug: "/guides/car-loan-interest-calculator-guide-malaysia", title: "Car Loan Interest Calculator Guide", inbound: 4, outbound: 3, risk: "ok" },
  { slug: "/guides/motorcycle-loan-guide-malaysia", title: "Motorcycle Loan Guide", inbound: 3, outbound: 2, risk: "ok" },
  { slug: "/guides/how-much-emergency-fund-malaysia", title: "How Much Emergency Fund", inbound: 2, outbound: 3, risk: "low" },
  { slug: "/guides/salary-rm4000-budget-plan-malaysia", title: "RM4,000 Budget Plan", inbound: 2, outbound: 4, risk: "low" },
  { slug: "/guides/salary-rm5000-budget-plan-malaysia", title: "RM5,000 Budget Plan", inbound: 2, outbound: 4, risk: "low" },
  { slug: "/guides/salary-rm6000-budget-plan-malaysia", title: "RM6,000 Budget Plan", inbound: 2, outbound: 4, risk: "low" },
  { slug: "/guides/how-to-save-first-rm10000-malaysia", title: "How to Save First RM10,000", inbound: 2, outbound: 4, risk: "low" },
  { slug: "/guides/best-savings-accounts-malaysia", title: "Best Savings Accounts", inbound: 2, outbound: 3, risk: "low" },
  { slug: "/guides/housing-loan-margin-of-finance-malaysia", title: "Housing Loan Margin of Finance", inbound: 2, outbound: 3, risk: "low" },
  { slug: "/guides/refinancing-guide-malaysia", title: "Refinancing Guide Malaysia", inbound: 2, outbound: 3, risk: "low" },
];

const orphans = INTERNAL_LINK_ANALYSIS.filter(p => p.risk === "orphan");
const lowLinks = INTERNAL_LINK_ANALYSIS.filter(p => p.risk === "low");
const healthy = INTERNAL_LINK_ANALYSIS.filter(p => p.risk === "ok");

const SEO_OPPORTUNITIES = [
  { priority: "High", opportunity: "Submit sitemap to Google Search Console after each Vercel deploy", pages: ["https://smartcalc-my.vercel.app/sitemap.xml"] },
  { priority: "High", opportunity: "Request Google indexing for all 20 Phase 2 guides via Search Console URL Inspection", pages: ["44 guides total — prioritise Phase 2 pages added 2026-06-22"] },
  { priority: "Medium", opportunity: "Create a 'Related guides' section at the bottom of each guide", pages: ["All 44 guides — currently guides link only via inline prose"] },
  { priority: "Medium", opportunity: "Add more guides to Footer curated list (currently 12 links)", pages: ["components/Footer.tsx — update Guides section"] },
  { priority: "Medium", opportunity: "Target 'loan calculator Malaysia' long-tail from Loan Calculator page (missing guides link)", pages: ["/loan-calculator → link to car-loan-interest-calculator-guide, refinancing-guide"] },
  { priority: "Low", opportunity: "Create a Sitemap HTML page at /sitemap for users (not robots)", pages: ["New page: app/sitemap-page/page.tsx"] },
  { priority: "Low", opportunity: "Add hreflang for Bahasa Malaysia (if BM content is ever added)", pages: ["app/layout.tsx"] },
];

const statusColors: Record<string, string> = {
  active: "bg-green-100 text-green-700",
  pending: "bg-yellow-100 text-yellow-700",
  inactive: "bg-red-100 text-red-700",
};

const riskColors: Record<string, string> = {
  ok: "bg-green-100 text-green-700",
  low: "bg-yellow-100 text-yellow-700",
  orphan: "bg-red-100 text-red-700",
};

const priorityColors: Record<string, string> = {
  High: "bg-red-100 text-red-700",
  Medium: "bg-yellow-100 text-yellow-700",
  Low: "bg-gray-100 text-gray-600",
};

export default function SeoDashboardPage() {
  return (
    <main className="min-h-screen bg-gray-50 text-gray-900">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between">
        <div>
          <div className="text-xs text-gray-400 mb-1">SmartCalc MY · Admin</div>
          <h1 className="text-xl font-bold text-gray-900">SEO Dashboard</h1>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-xs text-gray-400">Last updated: {SITE_STATS.lastUpdated}</span>
          <Link href="/" className="text-xs font-medium text-blue-600 hover:underline">← Back to site</Link>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-4 sm:px-6 py-8 space-y-10">

        {/* Site Overview */}
        <section>
          <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">Site Overview</h2>
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4">
            {[
              { label: "Total Pages", value: SITE_STATS.totalPages, color: "bg-blue-50 border-blue-100" },
              { label: "Guides", value: SITE_STATS.guides, color: "bg-teal-50 border-teal-100" },
              { label: "Calculators", value: SITE_STATS.calculators, color: "bg-violet-50 border-violet-100" },
              { label: "Static Pages", value: SITE_STATS.staticPages, color: "bg-gray-50 border-gray-200" },
              { label: "Sitemap URLs", value: SITE_STATS.sitemapUrls, color: "bg-orange-50 border-orange-100" },
              { label: "JSON-LD Schemas", value: SITE_STATS.guides + SITE_STATS.calculators, color: "bg-green-50 border-green-100" },
            ].map(({ label, value, color }) => (
              <div key={label} className={`rounded-xl border ${color} p-4 text-center`}>
                <div className="text-3xl font-bold text-gray-900">{value}</div>
                <div className="text-xs text-gray-500 mt-1">{label}</div>
              </div>
            ))}
          </div>
        </section>

        {/* Integration Status */}
        <section>
          <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">Integration & Verification Status</h2>
          <div className="bg-white rounded-2xl border border-gray-100 overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-100 bg-gray-50">
                  <th className="text-left px-5 py-3 font-semibold text-gray-600">Integration</th>
                  <th className="text-center px-4 py-3 font-semibold text-gray-600 w-24">Status</th>
                  <th className="text-left px-5 py-3 font-semibold text-gray-600">Detail</th>
                </tr>
              </thead>
              <tbody>
                {INTEGRATIONS.map((row) => (
                  <tr key={row.name} className="border-b border-gray-50 last:border-0">
                    <td className="px-5 py-3 font-medium text-gray-800">{row.name}</td>
                    <td className="px-4 py-3 text-center">
                      <span className={`text-xs font-semibold px-2.5 py-1 rounded-full ${statusColors[row.status]}`}>
                        {row.status}
                      </span>
                    </td>
                    <td className="px-5 py-3 text-gray-500 text-xs leading-relaxed">{row.detail}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* Internal Linking Report */}
        <section>
          <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-2">Internal Linking Report</h2>
          <p className="text-xs text-gray-400 mb-4">Inbound = other site pages linking to this page. Outbound = links from this page to other site pages. Risk is based on inbound link count.</p>

          {/* Summary */}
          <div className="grid grid-cols-3 gap-4 mb-6">
            <div className="bg-green-50 border border-green-100 rounded-xl p-4 text-center">
              <div className="text-2xl font-bold text-green-700">{healthy.length}</div>
              <div className="text-xs text-green-600 mt-1">Healthy (≥3 inbound)</div>
            </div>
            <div className="bg-yellow-50 border border-yellow-100 rounded-xl p-4 text-center">
              <div className="text-2xl font-bold text-yellow-700">{lowLinks.length}</div>
              <div className="text-xs text-yellow-600 mt-1">Low Links (1–2 inbound)</div>
            </div>
            <div className="bg-red-50 border border-red-100 rounded-xl p-4 text-center">
              <div className="text-2xl font-bold text-red-700">{orphans.length}</div>
              <div className="text-xs text-red-600 mt-1">Orphan Risk (≤1 inbound)</div>
            </div>
          </div>

          {/* Orphan pages — action needed */}
          {orphans.length > 0 && (
            <div className="mb-6">
              <h3 className="text-sm font-bold text-red-700 mb-3 flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-red-500 inline-block" />
                Orphan / Near-Orphan Pages — Needs Action
              </h3>
              <div className="bg-white rounded-xl border border-red-100 overflow-hidden">
                <table className="w-full text-sm">
                  <thead><tr className="bg-red-50 border-b border-red-100"><th className="text-left px-4 py-2.5 font-semibold text-gray-600">Page</th><th className="text-center px-4 py-2.5 font-semibold text-gray-600">Inbound</th><th className="text-center px-4 py-2.5 font-semibold text-gray-600">Outbound</th><th className="text-center px-4 py-2.5 font-semibold text-gray-600">Risk</th></tr></thead>
                  <tbody>
                    {orphans.map(p => (
                      <tr key={p.slug} className="border-b border-gray-50 last:border-0">
                        <td className="px-4 py-2.5"><Link href={p.slug} className="text-blue-600 hover:underline font-medium">{p.title}</Link><div className="text-xs text-gray-400">{p.slug}</div></td>
                        <td className="px-4 py-2.5 text-center font-bold text-red-600">{p.inbound}</td>
                        <td className="px-4 py-2.5 text-center text-gray-600">{p.outbound}</td>
                        <td className="px-4 py-2.5 text-center"><span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${riskColors[p.risk]}`}>{p.risk}</span></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Low link pages */}
          <div className="mb-6">
            <h3 className="text-sm font-bold text-yellow-700 mb-3 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-yellow-500 inline-block" />
              Low Internal Links — Monitor
            </h3>
            <div className="bg-white rounded-xl border border-yellow-100 overflow-hidden">
              <table className="w-full text-sm">
                <thead><tr className="bg-yellow-50 border-b border-yellow-100"><th className="text-left px-4 py-2.5 font-semibold text-gray-600">Page</th><th className="text-center px-4 py-2.5 font-semibold text-gray-600">Inbound</th><th className="text-center px-4 py-2.5 font-semibold text-gray-600">Outbound</th><th className="text-center px-4 py-2.5 font-semibold text-gray-600">Risk</th></tr></thead>
                <tbody>
                  {lowLinks.map(p => (
                    <tr key={p.slug} className="border-b border-gray-50 last:border-0">
                      <td className="px-4 py-2.5"><Link href={p.slug} className="text-blue-600 hover:underline font-medium">{p.title}</Link><div className="text-xs text-gray-400">{p.slug}</div></td>
                      <td className="px-4 py-2.5 text-center font-semibold text-yellow-600">{p.inbound}</td>
                      <td className="px-4 py-2.5 text-center text-gray-600">{p.outbound}</td>
                      <td className="px-4 py-2.5 text-center"><span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${riskColors[p.risk]}`}>{p.risk}</span></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Healthy pages — collapsed summary */}
          <details className="bg-white rounded-xl border border-green-100">
            <summary className="px-5 py-3.5 cursor-pointer text-sm font-semibold text-green-700 list-none flex items-center justify-between">
              <span className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-green-500 inline-block" />Healthy Pages ({healthy.length})</span>
              <span className="text-xs text-gray-400 font-normal">click to expand</span>
            </summary>
            <div className="border-t border-green-50 overflow-x-auto">
              <table className="w-full text-sm">
                <thead><tr className="bg-green-50 border-b border-green-50"><th className="text-left px-4 py-2.5 font-semibold text-gray-600">Page</th><th className="text-center px-4 py-2.5 font-semibold text-gray-600">Inbound</th><th className="text-center px-4 py-2.5 font-semibold text-gray-600">Outbound</th></tr></thead>
                <tbody>
                  {healthy.map(p => (
                    <tr key={p.slug} className="border-b border-gray-50 last:border-0">
                      <td className="px-4 py-2.5"><Link href={p.slug} className="text-blue-600 hover:underline font-medium">{p.title}</Link></td>
                      <td className="px-4 py-2.5 text-center font-semibold text-green-700">{p.inbound}</td>
                      <td className="px-4 py-2.5 text-center text-gray-600">{p.outbound}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </details>
        </section>

        {/* Calculators */}
        <section>
          <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">Calculators &amp; Target Keywords</h2>
          <div className="bg-white rounded-2xl border border-gray-100 overflow-hidden">
            <table className="w-full text-sm">
              <thead><tr className="bg-gray-50 border-b border-gray-100"><th className="text-left px-5 py-3 font-semibold text-gray-600">Calculator</th><th className="text-left px-5 py-3 font-semibold text-gray-600">Primary Keywords</th></tr></thead>
              <tbody>
                {CALCULATORS.map(c => (
                  <tr key={c.slug} className="border-b border-gray-50 last:border-0">
                    <td className="px-5 py-3"><Link href={c.slug} className="text-blue-600 hover:underline font-medium">{c.title}</Link></td>
                    <td className="px-5 py-3 text-gray-500 text-xs">{c.keywords.join(" · ")}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* SEO Opportunities */}
        <section>
          <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">SEO Opportunities — Action List</h2>
          <div className="space-y-3">
            {SEO_OPPORTUNITIES.map((opp, i) => (
              <div key={i} className="bg-white rounded-xl border border-gray-100 px-5 py-4">
                <div className="flex items-start gap-3">
                  <span className={`text-xs font-bold px-2.5 py-1 rounded-full flex-shrink-0 mt-0.5 ${priorityColors[opp.priority]}`}>{opp.priority}</span>
                  <div>
                    <div className="font-semibold text-gray-800 text-sm">{opp.opportunity}</div>
                    <div className="text-xs text-gray-400 mt-1">{opp.pages.join(" · ")}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Sitemap Preview */}
        <section>
          <h2 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">Sitemap URLs ({SITE_STATS.sitemapUrls} total)</h2>
          <div className="bg-white rounded-2xl border border-gray-100 p-5">
            <div className="flex gap-3 mb-4">
              <Link href="/sitemap.xml" target="_blank" className="text-xs font-semibold bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors">View sitemap.xml →</Link>
              <Link href="/robots.txt" target="_blank" className="text-xs font-semibold bg-gray-100 text-gray-700 px-4 py-2 rounded-lg hover:bg-gray-200 transition-colors">View robots.txt →</Link>
            </div>
            <p className="text-xs text-gray-500">
              Submit to Google Search Console: <code className="bg-gray-100 px-2 py-0.5 rounded text-xs">https://smartcalc-my.vercel.app/sitemap.xml</code>
            </p>
            <p className="text-xs text-gray-400 mt-2">Sitemap is auto-generated from <code className="bg-gray-100 px-1.5 py-0.5 rounded text-xs">app/sitemap.ts</code>. Add new pages there after each content push.</p>
          </div>
        </section>

        {/* Footer */}
        <div className="text-center text-xs text-gray-400 pb-8">
          SmartCalc MY Admin · SEO Dashboard · Not indexed by search engines
        </div>
      </div>
    </main>
  );
}
