import type { Metadata } from "next";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Use — SmartCalc MY",
  description:
    "Terms of use for SmartCalc MY. Understand the conditions governing your use of our free Malaysian calculators, including our disclaimer on estimates.",
  alternates: { canonical: "/terms" },
  robots: { index: true, follow: true },
};

const EFFECTIVE_DATE = "17 June 2025";
const CONTACT_EMAIL = "hello@smartcalc.my";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-lg font-bold text-gray-900 mb-3">{title}</h2>
      <div className="text-gray-600 text-sm leading-relaxed space-y-3">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="flex-1 bg-gray-50">
        {/* Hero */}
        <section className="bg-white border-b border-gray-100">
          <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-14 text-center">
            <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-3">Terms of Use</h1>
            <p className="text-gray-500 text-sm">Effective date: {EFFECTIVE_DATE}</p>
          </div>
        </section>

        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          {/* Key disclaimer callout */}
          <div className="bg-amber-50 border border-amber-200 rounded-2xl p-5 sm:p-6 mb-8">
            <div className="flex items-start gap-3">
              <svg className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
              </svg>
              <div>
                <p className="font-bold text-amber-800 mb-1">All calculator results are estimates only</p>
                <p className="text-amber-700 text-sm leading-relaxed">
                  SmartCalc MY calculators are informational tools. Results do not constitute financial, medical, tax, or legal advice. Always verify with qualified professionals or official sources before making any decisions.
                </p>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 sm:p-10 space-y-8">
            <p className="text-gray-600 text-sm leading-relaxed">
              These Terms of Use (&quot;Terms&quot;) govern your access to and use of the SmartCalc MY website at smartcalc.my (the &quot;Site&quot;) and all tools, content, and services provided therein. By accessing or using the Site, you agree to be bound by these Terms.
            </p>

            <Section title="1. Acceptance of Terms">
              <p>By using the Site, you confirm that you are at least 13 years of age and agree to comply with these Terms. If you do not agree, please do not use the Site.</p>
            </Section>

            <Section title="2. Nature of the Service">
              <p>SmartCalc MY provides free online calculators for informational and educational purposes, including:</p>
              <ul className="list-disc list-inside space-y-1 pl-2">
                <li><strong>BMI Calculator:</strong> Estimates body mass index using WHO Asia-Pacific guidelines.</li>
                <li><strong>Salary Calculator:</strong> Estimates take-home pay using Malaysian statutory rates (EPF, SOCSO, EIS, PCB).</li>
                <li><strong>Loan Calculator:</strong> Estimates monthly repayments using reducing-balance amortisation.</li>
              </ul>
            </Section>

            <Section title="3. Disclaimer of Estimates">
              <p>All results generated by our calculators are <strong>estimates based on standard assumptions</strong> and publicly available statutory rates. They are provided for general informational purposes only and:</p>
              <ul className="list-disc list-inside space-y-1 pl-2">
                <li>Do <strong>not</strong> constitute financial, tax, medical, investment, or legal advice.</li>
                <li>May not reflect your personal circumstances, declared reliefs, employer arrangements, or bank-specific terms.</li>
                <li>May not be accurate for hire-purchase (flat-rate) loans, civil servants, or non-resident individuals.</li>
                <li>Are not a substitute for professional advice or official correspondence from LHDN, EPF, SOCSO, or your bank.</li>
              </ul>
              <p>Always verify results independently and consult a qualified professional before making any financial, health, or legal decision.</p>
            </Section>

            <Section title="4. Accuracy of Information">
              <p>We make reasonable efforts to keep our calculators up-to-date with current Malaysian statutory rates and guidelines. However, we do not warrant that the information on the Site is complete, accurate, current, or free from errors. Statutory rates may change and there may be a delay before our calculators reflect such changes.</p>
            </Section>

            <Section title="5. No Professional Relationship">
              <p>Use of the Site does not create any professional relationship (financial advisory, medical, legal, or otherwise) between you and SmartCalc MY. We are not licensed financial advisors, tax agents, medical practitioners, or legal practitioners.</p>
            </Section>

            <Section title="6. Limitation of Liability">
              <p>To the fullest extent permitted by applicable Malaysian law, SmartCalc MY, its operators, and contributors shall not be liable for any direct, indirect, incidental, consequential, or special damages arising from:</p>
              <ul className="list-disc list-inside space-y-1 pl-2">
                <li>Your reliance on calculator results or any content on the Site.</li>
                <li>Errors, omissions, or inaccuracies in the calculator outputs.</li>
                <li>Any interruption or unavailability of the Site.</li>
                <li>Any third-party content or advertisements displayed on the Site.</li>
              </ul>
            </Section>

            <Section title="7. Intellectual Property">
              <p>All content on the Site — including text, design, code, and calculator logic — is the property of SmartCalc MY and is protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works from any part of the Site without our prior written consent.</p>
            </Section>

            <Section title="8. Third-Party Advertising">
              <p>The Site displays advertisements served by Google AdSense and potentially other third-party advertising networks. We are not responsible for the content, accuracy, or practices of any advertiser. Clicking on advertisements may take you to third-party websites governed by their own terms and privacy policies.</p>
            </Section>

            <Section title="9. Acceptable Use">
              <p>You agree not to:</p>
              <ul className="list-disc list-inside space-y-1 pl-2">
                <li>Use the Site for any unlawful purpose or in violation of any applicable law.</li>
                <li>Attempt to access, scrape, or reproduce the Site's content or calculator logic without authorisation.</li>
                <li>Interfere with or disrupt the Site's infrastructure or security.</li>
                <li>Misrepresent the accuracy or authority of our calculator results.</li>
              </ul>
            </Section>

            <Section title="10. Modifications to the Site and Terms">
              <p>We reserve the right to modify, suspend, or discontinue any part of the Site at any time without notice. We may also update these Terms periodically. Continued use of the Site after changes are posted constitutes your acceptance of the revised Terms.</p>
            </Section>

            <Section title="11. Governing Law">
              <p>These Terms shall be governed by and construed in accordance with the laws of Malaysia. Any disputes arising from your use of the Site shall be subject to the exclusive jurisdiction of the courts of Malaysia.</p>
            </Section>

            <Section title="12. Contact">
              <p>
                For questions about these Terms, contact us at:{" "}
                <a href={`mailto:${CONTACT_EMAIL}`} className="text-blue-600 hover:underline">{CONTACT_EMAIL}</a>.
                See also our <Link href="/privacy-policy" className="text-blue-600 hover:underline">Privacy Policy</Link>.
              </p>
            </Section>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
